## @file
# Assign reviewers from a REVIEWERS file using CODEOWNERS syntax
#
# Copyright (c) 2022, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: Assign reviewers from a REVIEWERS file using CODEOWNERS syntax

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - 'dev/GitHubActions/main'
      - 'dev/GitHubActions/stable/**'

jobs:
  assign_reviewers:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mdkinney/github-action-assign-reviewers@b5573ac2626d030fa6f7d963abac152c87445b51
        with:
          token: ${{secrets.GITHUB_TOKEN}}
